129 add bayesian optimization
RWTH-EBC/ebcpy pull request #137
Opened 2024-07-15 08:56 UTC by jkriwet

Closes #129

2024-07-15 12:29 UTC, FWuellhorst requested changes
@jkriwet Thanks for the feature!
Can you further:
- include the option in the example for optimization?
- Increase the version number to 0.5.0 due to the new feature? Also add the changelog.

2024-07-15 12:29 UTC, FWuellhorst commented on ebcpy/optimization.py
> +        For an explanation of what the parameters do, please refer to the documentation of
we refer

2024-07-15 12:29 UTC, FWuellhorst commented on ebcpy/optimization.py
> +        return -self.obj(xk)
I am not sure if this always applies. My student used it without `-` for exploration. Maybe set an option for exploration vs. exploitation? Let's discuss internally.

2024-07-17 15:06 UTC, FWuellhorst commented
@jkriwet : When doing the review, can you add the following kwarg?
```
"""gp = None"""
gp = kwargs.get("gp", None)
if gp is not None:
    optimizer._gp = gp
```

2024-08-14 10:58 UTC, jkriwet commented on ebcpy/optimization.py
> +        For an explanation of what the parameters do, please refer to the documentation of
Done

2024-08-14 10:58 UTC, jkriwet commented on ebcpy/optimization.py
> +        return -self.obj(xk)
As discussed, no need to change

2024-08-14 11:07 UTC, jkriwet commented
> @jkriwet : When doing the review, can you add the following kwarg?
> 
> ```
> """gp = None"""
> gp = kwargs.get("gp", None)
> if gp is not None:
>     optimizer._gp = gp
> ```

Done

2024-08-15 06:03 UTC, FWuellhorst commented
@jkriwet : Looks really nice the new feature and example! I further added markers to see which point is where.
pymoo seems to have resolved the issue in their latest version, but removed all factories to avoid development efforts for them. This would mean we have to maintain a dict for string-class relation of pymoo objects, which I would not do to avoid overhead. 
If the new pymoo version is of interest, we could remove the option to pass a string and just have users import the class beforehand.

2024-08-15 06:04 UTC, FWuellhorst approved these changes

2024-08-15 08:57 UTC, jkriwet commented on setup.py
> +        'bayesian-optimization==1.5.1',
Changed to version in the requirements. 1.5.1 works, but not for python version <= 3.9 (or 3.8). Since nothing important is changed in 1.5.1, fixing to 1.4.3 for now

2024-08-15 09:20 UTC, merged