81 support for parquet
RWTH-EBC/ebcpy pull request #85
Opened 2023-02-09 10:25 UTC by HvanderStok

Solves #81, and additionally, hdf is now supported for the new python versions.
I also did a little comparison of some data types to showcase the options of parquet and their performance. For that, I tested the saving and loading time for a TimeSeriesData with 100000 rows and 5 columns and repeated the test 1000 times to get the mean value and standard deviation.
With parquet, we can use 3 additional compressions and two engines. Following, the results are shown for all options:

Time saving data with pyarrow:
```
                    mean       std       min       max     bytes
csv             2.353726  0.131802  2.318471  5.112420  21183673
hdf             0.039329  0.005107  0.035627  0.135489   8986376
parquet         0.120364  0.008838  0.114131  0.314028  11149595
parquet.snappy  0.124590  0.005329  0.118496  0.187414  11141303
parquet.gzip    0.691296  0.008751  0.680176  0.755640  10345249
parquet.brotli  0.690288  0.008681  0.679464  0.777547  10345249
```
Time loading data with pyarrow:
```
                    mean       std       min       max     bytes
csv             0.290358  0.005503  0.282977  0.321121  21183673
hdf             0.026670  0.001378  0.024445  0.035852   8986376
parquet         0.018074  0.001014  0.016468  0.036453  11149595
parquet.snappy  0.019595  0.001071  0.018007  0.034390  11141303
parquet.gzip    0.024822  0.001469  0.022991  0.047755  10345249
parquet.brotli  0.024467  0.000921  0.023044  0.034593  10345249
```

Time saving data with fastparquet:
```
                    mean       std       min       max     bytes
csv             2.452787  0.096346  2.412802  4.106544  21183673
parquet         0.055180  0.003508  0.051635  0.114354   8803903
parquet.snappy  0.057947  0.004831  0.054621  0.154641   8795446
parquet.gzip    0.470162  0.006608  0.460986  0.530863   8146963
parquet.brotli  0.470039  0.006415  0.461267  0.514552   8146963
```
Time loading data with fastparquet:
```
                    mean       std       min       max     bytes
csv             0.285539  0.003496  0.282039  0.308510  21183673
parquet         0.009437  0.000590  0.009009  0.014709   8803903
parquet.snappy  0.010560  0.000716  0.010065  0.015259   8795446
parquet.gzip    0.052438  0.001568  0.051464  0.068386   8146963
parquet.brotli  0.052189  0.000843  0.051506  0.060770   8146963
```

2023-02-10 16:37 UTC, FWuellhorst requested changes
Thanks for the nice feature!!

Three things:
1. Please update version number by a minor, this change is a new feature
2. Please check my comments and decline / accept the requested changes.
3. Please write the speed comparison into the issue. You can also add the issue-link into the doc-section of the TimeSeriesData object for better reference :)

2023-02-10 16:37 UTC, FWuellhorst commented on ebcpy/data_types.py
> +        elif filepath.suffix == ".parquet":
This could be further reduced in code length:

```
parquet_split = filename.name.split(".parquet")
if len(parquet_split) == 1:
    raise TypeError ...  # .parquet not in name
pd.DataFrame(self).to_parquet(filepath, engine=kwargs.get('engine', 'pyarrow'),
                               compression=parquet_split[-1] if parquet_split[-1] else None,
                               index=True)
```
This assumes that to_parquet raises an error for wrong compression inputs. If they don't, we could write a helper function like:
```
def get_compression(suffix_split: str):
    if not suffix_split:
        return None
    if suffix_plit not in ["gzip", "snappy", ...]:
        raise TypeError
    return suffix_split
```

This way, we avoid the long if-statements during saving and loading and are flexible if pandas adds new compression engines.
What do you think?

2023-02-10 16:37 UTC, FWuellhorst commented on setup.py
> +    EXTRAS_REQUIRE['full'].append('pyarrow>=11.0.0')
This should always be the case. I will remove the 3.6 test. You can delete this.

2023-02-10 16:37 UTC, FWuellhorst commented on tests/test_data_types.py
> +        parquet_formats = ['parquet', 'parquet.snappy', 'parquet.gzip', 'parquet.brotli']
Maybe we can add a "parquet_compression_types" class attribute to `TimeSeriesData` which we can use in here and in the dynamic loading function?

2023-02-14 14:10 UTC, HvanderStok commented on ebcpy/data_types.py
> +        elif filepath.suffix == ".parquet":
I reduced the if statements and now all compression from the parquet engines are supported, and these engines throw an error if the compression is supported. They also support more compressions than currently mentioned by pandas. I will make a new comparison for all currently possible options and add it to the issue as soon as possible.

2023-02-16 09:45 UTC, FWuellhorst approved these changes
Thanks for the nice feature :) 

We have to wait for CI to pass, the tests are no working for Dymola as well. You can then check coverage rate.

2023-03-13 07:42 UTC, FWuellhorst commented on tests/test_simulationapi.py
> +            dymola_path = "/opt/dymola-2020-x86_64"
I have to update the docker image :)

2023-03-14 10:52 UTC, merged