86 storage space and time estimation
RWTH-EBC/ebcpy pull request #90
Opened 2023-02-23 11:14 UTC by HvanderStok

Closes #86

2023-03-13 14:00 UTC, FWuellhorst requested changes
Only minor doc string changes requested

2023-03-13 14:00 UTC, FWuellhorst commented on ebcpy/simulationapi/__init__.py
> +            print(" ")
Why is the print necessary? Print should be avoided in pypi packages.

Ok, I see it further down below. Is it possible to do the same for logging as well?

2023-03-13 14:00 UTC, FWuellhorst commented on ebcpy/simulationapi/__init__.py
> +        start-up time is not considered in the time estimation.
start-up time (e.g. translation)

2023-03-13 14:00 UTC, FWuellhorst commented on ebcpy/simulationapi/__init__.py
> +            Start time after n_cpu simulations.
Depending on the case, the first 10 simulations on 10 cores may be executed on e.g. 6 cores only, if the simulation is really fast for instance. 
Please note, that this is just an assumption. (in line 338 as a comment)

2023-03-13 14:00 UTC, FWuellhorst commented on ebcpy/simulationapi/__init__.py
> +        Works only for multiprocessing.
Note the 5 % assumption in the doc

2023-03-14 10:37 UTC, HvanderStok commented on ebcpy/simulationapi/__init__.py
> +            print(" ")
I have changed the `print` statements to `sys.stderr.write`. Is this maybe better? Unfortunately, it is in my opinion not nicely possible to achieve it with the logging module.

2023-03-14 11:09 UTC, FWuellhorst approved these changes
Thanks for the nice feature and work!

2023-03-14 11:23 UTC, merged